language: generic
services:
    - docker

jobs:
  include:
    - stage: stage1-build
      name: "Build exasol icinga container for stage1"
      script:
      - echo "exaexaexa" | docker login -u "dschlieder" --password-stdin
      - docker build -t exasol/icinga-monitoring:stage1 -f Dockerfile .
      - docker images
      - docker tag exasol/icinga-monitoring:stage1 dschlieder/parking:stage1
      - docker push dschlieder/parking:stage1
    - stage: stage1-test
      name: "Create and test exasol icinga stage1 container (basic)"
      script:
      - docker create --name exasol-icinga --hostname exasol-icinga dschlieder/parking:stage1
      - docker start exasol-icinga && sleep 30s && docker exec exasol-icinga bash -c 'pgrep icinga2 && pgrep apache2 && pgrep mysqld'
stages:
  - stage1-build
  - stage1-test
