language: generic
services:
    - docker

jobs:
  include:
    - stage: stage1-build
      name: "Build exasol icinga container for stage1"
      script:
      - echo "exaexaexa" | docker login -u "dschlieder" --password-stdin
      - docker build -t exasol/icinga-monitoring:stage1 -f Dockerfile .
      - docker images
      - docker tag exasol/icinga-monitoring:stage1 dschlieder/parking:stage1
      - docker push dschlieder/parking:stage1
    - stage: stage1-test
      name: "Create and test exasol icinga stage1 container (basic)"
      script:
      - docker create --name exasol-icinga --hostname exasol-icinga dschlieder/parking:stage1
      - docker start exasol-icinga && sleep 30s 
      - docker exec exasol-icinga bash -c 'pgrep icinga2 && pgrep apache2 && pgrep mysqld'
      - docker exec exasol-icinga bash -c 'TEST=$( wget -S  http://icingaadmin:admin@localhost/icingaweb2/ 2>&1 |grep HTTP/ | tail -n 1) && if [[ "$TEST" == "  HTTP/1.1 200 OK" ]]; then echo "success" && /bin/true; else echo "failed" && /bin/false; fi'
    - stage: stage2-build
      name: "Build exasol icinga container for stage2"
      script:
      - echo "I am just a placeholder for now" 
      - /bin/true
    - stage: stage2-test
      name: "Create and test exasol icinga container for stage2"
      script:
      - echo "I am just a placeholder for now" 
      - /bin/true
    - stage: stage3-build
      name: "Build exasol icinga container for stage3"
      script:
      - echo "I am just a placeholder for now" 
      - /bin/true
    - stage: stage3-test
      name: "Create and test exasol icinga container for stage3"
      script:
      - echo "I am just a placeholder for now" 
      - /bin/true
stages:
  - stage1-build
  - stage1-test
  - stage2-build
  - stage2-test
  - stage3-build
  - stage3-test
