language: generic
services:
    - docker
script:
    - git clone https://github.com/EXASOL/nagios-monitoring
    - docker build -t exasol/nagios-monitoring:latest -f Dockerfile .
    - docker create --name exasol-nagios --hostname exasol-nagios exasol/nagios-monitoring:latest
    - docker start exasol-nagios
    - docker exec exasol-nagios pgrep nagios
    - docker exec exasol-nagios pgrep lighttpd
    - docker exec exasol-nagios pgrep php-cgi
