#!/bin/bash
export PATH="$PATH:/opt/nagios4/bin:/opt/nagios4/sbin:/opt/pnp4nagios/bin"
chmod u+s /bin/ping /bin/ping6
generate-certificate
download-odbc-driver
service cron start

(LC_ALL=C 
    service nagios start;
    service npcd start;
    service lighttpd start;
)

#don't close init process:
while true; do sleep 60; done;
