#!/bin/sh

#
#   Copyright (C) 2014-2015 Fujitsu Technology Solutions GmbH. All Rights Reserved.
#

# version string
# Version:	3.30.02
# Version:	3.20.00
# Date:		2015-07-27

#
# init_cimlistenerd.sh
#
# chkconfig: 35 98 01
# description: Starts and stops the FTS CIM indication listener daemon
#


### BEGIN INIT INFO
# Provides:          svcimlistenerd
# Required-Start:    $syslog
# Should-Start:      $time $network $remote_fs
# Required-Stop:     $syslog
# Should-Stop:       $time $network $remote_fs
# Default-Start:     3 5
# Default-Stop:      0 1 2 4 6
# Short-Description: Starts and stops CIM listener daemon
# Description:       Starts and stops CIM listener daemon
### END INIT INFO


wait_daemon()
{
    i=1
    rets=10
    svcimlistenerd status
    while [ $? -ne 0 -a $i -lt $rets ]; do
        sleep 1
        echo -n .
        i=$(($i + 1))
        svcimlistenerd status
    done
}

# check if rc.status is available
test -r /etc/rc.status
RC_STATUS=$?
if [ $RC_STATUS = 0 ]; then
    . /etc/rc.status
    rc_reset
fi

if [ "$1" != status -a "_$1" != "_" ] && [ `id -u` != 0 ]; then
    echo -n "svcimlistenerd "
    if [ ! $RC_STATUS ]; then
        rc_failed 4
        rc_status -v
        rc_exit
    else 
        echo ': permission denied'
        exit;
    fi
fi

CIMLISTENER=`ps ax | grep svcimlistenerd | grep perl | awk '{ print $1 }'`
CIMLISTENER=`echo $CIMLISTENER`

case "$1" in
    start)
        echo -n "Starting CIM listener daemon "
        if [ ! -z "$CIMLISTENER" ]; then
            echo -n "(already running pid $CIMLISTENER) "
        fi

        svcimlistenerd start

        if [ $RC_STATUS != 0 ]
        then
            if wait_daemon; then echo ': done'
            else echo ': failed'
            fi
            exit
        else
            wait_daemon
        fi
        ;;
    stop)
        echo -n "Stopping CIM listener daemon "
        if [ -z "$CIMLISTENER" ]; then
            echo -n "(not running) "
        else
            echo -n "(pid $CIMLISTENER) "
        fi

        if [ $RC_STATUS != 0 ]
        then
            if svcimlistenerd stop; then echo ': done'
            else echo ': failed'
            fi            
            exit
        else
            svcimlistenerd stop
            rc_reset
        fi
        ;;
    status)
        echo -n "Checking status of CIM listener daemon "
        if [ ! -z "$CIMLISTENER" ]; then
            echo -n "(pid $CIMLISTENER) "
        fi

        if [ $RC_STATUS != 0 ]
        then
            svcimlistenerd status
            case $? in
            3) echo ': not running';;
            0) echo ': running';;
            *) echo ': failed';;
            esac
            exit
        else
            svcimlistenerd status
        fi
        ;;
    restart)
        echo -n "Restarting CIM listener daemon "
        if [ -z "$CIMLISTENER" ]; then
            echo -n "(not running) "
        else
            echo -n "(old pid $CIMLISTENER) "
        fi

        svcimlistenerd restart

        if [ $RC_STATUS != 0 ]
        then
            if wait_daemon; then echo ': done'
            else echo ': failed'
            fi
            exit
        else
            wait_daemon
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        if [ $RC_STATUS != 0 ]
        then
            exit
        else
            rc_failed 2
            rc_exit
        fi        
esac

rc_status -v
rc_exit
